[build]
rustflags = [
  "--cfg", "mls_build_async",
]

[target.aarch64-linux-android]
rustflags = ["--cfg", "mls_build_async", "-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.armv7-linux-androideabi]
rustflags = ["--cfg", "mls_build_async"]

[target.i686-linux-android]
rustflags = ["--cfg", "mls_build_async"]

[target.x86_64-linux-android]
rustflags = ["--cfg", "mls_build_async"]